apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  sources:
    - repoURL: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
      chart: arc
      targetRevision: 0.13.0
      helm:
        valueFiles:
          - $infra/apps/argocd-image-updater/values.yaml
    - repoURL: https://github.com/overburrow/infra.git
      targetRevision: main
      ref: infra
    - repoURL: https://github.com/overburrow/infra.git
      targetRevision: main
      path: apps/actions-runner-controller/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: actions-runner-controller
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
