apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argocd-image-updater
      targetRevision: 1.0.3
      helm:
        valueFiles:
          - $infra/apps/argocd-image-updater/values.yaml
    - repoURL: https://github.com/overburrow/infra.git
      targetRevision: main
      ref: infra
    - repoURL: https://github.com/overburrow/infra.git
      targetRevision: main
      path: apps/argocd-image-updater/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
