apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: cloudflared-infisical-secret
  namespace: cloudflared
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  hostAPI: https://infisical.overburrow.dev
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "overburrow"
        secretsPath: "/cloudflared"
        envSlug: "prod"
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: infisical

  managedKubeSecretReferences:
    - secretName: cloudflared-secret
      secretNamespace: cloudflared
      template:
        includeAllSecrets: true
