apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: gha-runner-infisical-secret
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  hostAPI: https://infisical.overburrow.dev
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "overburrow"
        secretsPath: "/gha-runner"
        envSlug: "prod"
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: infisical

  managedKubeSecretReferences:
    - secretName: gha-runner-secret
      secretNamespace: gha-runner
      template:
        includeAllSecrets: true
