githubConfigSecret: gha-runner-secret
githubConfigUrl: "https://github.com/overburrow"

controllerServiceAccount:
  name: gha-runner-controller-gha-rs-controller
  namespace: gha-runner

containerMode:
  type: "dind"
