githubConfigSecret: gha-runner-secret
githubConfigUrl: "https://github.com/overburrow"

controllerServiceAccount:
  name: gha-runner-controller-gha-rs-controller
  namespace: gha-runner

containerMode:
  type: "dind"

template:
  spec:
    containers:
      - name: dind
        volumeMounts:
          - name: dind-storage
            mountPath: /var/lib/docker
    volumes:
      - name: dind-storage
        persistentVolumeClaim:
          claimName: gha-runner-dind-pvc
