apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: argocd-image-updater-infisical-secret
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  hostAPI: https://infisical.overburrow.dev
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "overburrow"
        secretsPath: "/argocd-image-updater"
        envSlug: "prod"
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: infisical

  managedKubeSecretReferences:
    - secretName: argocd-image-updater-secrets
      secretNamespace: argocd
      template:
        includeAllSecrets: true
