apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: actions-runner-controller-infisical-secret
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  hostAPI: https://infisical.overburrow.dev
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "overburrow"
        secretsPath: "/actions-runner-controller"
        envSlug: "prod"
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: infisical

  managedKubeSecretReferences:
    - secretName: actions-runner-controller-secret
      secretNamespace: actions-runner-controller
      template:
        includeAllSecrets: true
