apiVersion: argoproj.io/v1alpha1
kind: ApplicationList
items:
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: infisical
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "3"
    spec:
      project: default
      sources:
        - repoURL: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
          chart: infisical-standalone
          targetRevision: 1.7.2
          helm:
            valueFiles:
              - $infra/apps/infisical/values.yaml
        - repoURL: https://github.com/overburrow/infra.git
          targetRevision: main
          ref: infra
      destination:
        server: https://kubernetes.default.svc
        namespace: infisical
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: infisical-operator
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "2"
    spec:
      project: default
      sources:
        - repoURL: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
          chart: secrets-operator
          targetRevision: 0.10.17
      destination:
        server: https://kubernetes.default.svc
        namespace: infisical
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
