apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: https://community-charts.github.io/helm-charts
      chart: cloudflared
      targetRevision: 2.2.4
      helm:
        valueFiles:
          - $infra/apps/cloudflared/values.yaml
    - repoURL: https://github.com/overburrow/infra.git
      targetRevision: main
      ref: infra
    - repoURL: https://github.com/overburrow/infra.git
      targetRevision: main
      path: apps/cloudflared/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflared
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
