replica:
  # set to false to use Deployment instead of DaemonSet
  allNodes: false
  count: 2

tunnelSecrets:
  existingConfigJsonFileSecret:
    name: cloudflared-secret
    key: credentials

tunnelConfig:
  name: "7446ad96-71fb-4b84-ac97-f06a17797ae8"

ingress:
  - hostname: overburrow.org
    service: http://traefik.kube-system.svc.cluster.local:8000
  - hostname: "*.overburrow.org"
    service: http://traefik.kube-system.svc.cluster.local:8000
  - service: http_status:404 # catch-all
