replica:
  allNodes: false
  count: 2

tunnelConfig:
  protocol: http2

tunnelSecrets:
  base64EncodedPemFile: "ZHVtbXk=" # base64 encoding of "dummy"; cloudflared chart requires this field but we only use the credentials file
  existingConfigJsonFileSecret:
    name: cloudflared-secret
    key: credentials

tunnelConfig:
  name: "7446ad96-71fb-4b84-ac97-f06a17797ae8"

ingress:
  - hostname: overburrow.org
    service: http://traefik.kube-system.svc.cluster.local:8000
  - hostname: "*.overburrow.org"
    service: http://traefik.kube-system.svc.cluster.local:8000
  - service: http_status:404 # catch-all
